spock <- read.csv("~/Documents/Stat217Fall2014/Projects/Project1/spockData.csv")
spock$judge <- as.factor(spock$judge)
require(mosaic)
favstats(percent~judge, data = spock)
boxplot(percent~judge, data = spock, ylab = "% Women in Venire")
points(percent~judge, data = spock, col = as.numeric(judge), pch = 20)
fit.spock<-lm(percent~judge, data = spock)
anova(fit.spock)
par(mfrow = c(2,2))
plot(fit.spock)
require(multcomp)
pairs <- glht(fit.spock, linfct=mcp(judge = "Tukey"))
confint(pairs)
plot(pairs)
require(gplots)
plotmeans(percent~judge, data=spock, mean.labels=F)
text(c(1:7),c(10,37,37,32,30,30,30),c("a", "b", "b","b", "ab", "b", "b")
     ,col=c("blue",rep("green", 3), "red", "green","green"),cex=2)
